Param = element param {
    attribute type { text },
    attribute name { text }
}

Constructor = element constructor {
    Param*
}

Handle = element handle {
    attribute name { text },
    Constructor,
}

Enum = element enum {
    attribute name { text },
    attribute value { text }
}

Result = element result {
    element success {
        attribute value { text },
        attribute name { text }
    },
    Enum*
}

element registry {
    attribute namespace { text },
    attribute diminutive { text },
    attribute prefix { text },
    Result,
    Handle+
}