strictBool = "true" | "false"

Param = element param {
    attribute type { text },
    attribute name { text }
}

Constructor = element constructor {
    Param*
}

Destructor = element destructor {
    attribute command { text },
    Param*
}

Property = element property {
    attribute type { text },
    attribute name { text },
    element get {
        attribute name { text }
    },
    element set {
        attribute name { text }
    }
}

Command = element command {
    attribute type { text },
    attribute name { text },
    Param*
}

Handle = element handle {
    attribute name { text },
    Constructor,
    Destructor,
    Property*,
    Command*
}

Enum = element enum {
    attribute name { text },
    attribute value { text }
}

Result = element result {
    element success {
        attribute value { text },
        attribute name { text }
    },
    Enum*
}

element registry {
    attribute namespace { text },
    attribute diminutive { text },
    attribute prefix { text },
    Result?,
    Handle+
}